# spell_template = {
#     "": {
#         "name": "",
#         "type": "",
#         "buff": False,
#         "healing": False,
#         "mp_cost": 0,
#         "mp_cost_percent": 0,
#         "sp_cost": 0,
#         "rage_cost": 0,
#         "enemy_dmg": 0,
#         "heal_amount": 0,
#         "mp_scaling_damage": 0,
#         "scaling_type": "",
#         "cast_time": 0,
#         "cooldown": 0,
#         "range": 0,
#         "aoe_radius": 0,
#         "accuracy": 0,
#         "projectile_speed": 0,
#         "damage_type": "",
#         "burn_chance": 0,
#         "burn_duration": 0,
#         "slow_chance": 0,
#         "slow_duration": 0,
#         "stun_chance": 0,
#         "stun_duration": 0,
#         "knockback": 0,
#         "lifesteal": 0,
#         "chain_targets": 0,
#         "purge_chance": 0,
#         "purge_duration": 0,
#         "self_damage": 0,
#         "buff": "",
#         "buff_value": 0,
#         "buff_duration": 0
#     }
# }


class SpellDataBase():
    spells = {

        #!! -- "Magic: Damage" ------------------------------------------------------------------------------------------------

        "fireball": {
            "name": "Fire Ball",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 5,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 24,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.1,
            "cooldown": 2.4,
            "range": 300,
            "aoe_radius": 45,
            "accuracy": 0.86,
            "projectile_speed": 8,
            "damage_type": "fire",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "ice_shard": {
            "name": "Ice Shard",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 6,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 18,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.0,
            "cooldown": 2.0,
            "range": 280,
            "aoe_radius": 0,
            "accuracy": 0.9,
            "projectile_speed": 10,
            "damage_type": "ice",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0.45,
            "slow_duration": 2.5,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "lightning_bolt": {
            "name": "Lightning Bolt",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 8,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 32,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.4,
            "cooldown": 3.0,
            "range": 350,
            "aoe_radius": 0,
            "accuracy": 0.82,
            "projectile_speed": 14,
            "damage_type": "electric",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0.28,
            "stun_duration": 1.0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "poison_dart": {
            "name": "Poison Dart",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 4,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 9,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.75,
            "cooldown": 1.5,
            "range": 320,
            "aoe_radius": 0,
            "accuracy": 0.95,
            "projectile_speed": 12,
            "damage_type": "poison",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "poison_damage": 6,
            "poison_duration": 4,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "arcane_blast": {
            "name": "Arcane Blast",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 10,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 38,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.9,
            "cooldown": 4.0,
            "range": 250,
            "aoe_radius": 60,
            "accuracy": 0.76,
            "projectile_speed": 6,
            "damage_type": "arcane",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "meteor": {
            "name": "Meteor",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 15,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 60,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 3.1,
            "cooldown": 6.5,
            "range": 400,
            "aoe_radius": 100,
            "accuracy": 0.72,
            "projectile_speed": 4,
            "damage_type": "fire",
            "burn_chance": 0.65,
            "burn_duration": 5,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "wind_slash": {
            "name": "Wind Slash",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 5,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 17,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.55,
            "cooldown": 1.7,
            "range": 260,
            "aoe_radius": 0,
            "accuracy": 0.91,
            "projectile_speed": 16,
            "damage_type": "wind",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 14,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "earth_spike": {
            "name": "Earth Spike",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 7,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 26,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.7,
            "cooldown": 3.5,
            "range": 240,
            "aoe_radius": 35,
            "accuracy": 0.8,
            "projectile_speed": 5,
            "damage_type": "earth",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0.22,
            "stun_duration": 1.0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "shadow_bolt": {
            "name": "Shadow Bolt",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 9,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 36,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.25,
            "cooldown": 3.0,
            "range": 330,
            "aoe_radius": 0,
            "accuracy": 0.86,
            "projectile_speed": 11,
            "damage_type": "dark",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0.22,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "chain_lightning": {
            "name": "Chain Lightning",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 12,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 23,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.5,
            "cooldown": 4.5,
            "range": 340,
            "aoe_radius": 0,
            "accuracy": 0.9,
            "projectile_speed": 13,
            "damage_type": "electric",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 3,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "frost_nova": {
            "name": "Frost Nova",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 11,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 14,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.3,
            "cooldown": 5.0,
            "range": 0,
            "aoe_radius": 120,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "ice",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 1.0,
            "slow_duration": 3.0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "inferno_pulse": {
            "name": "Inferno Pulse",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 14,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 52,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 2.1,
            "cooldown": 5.5,
            "range": 260,
            "aoe_radius": 80,
            "accuracy": 0.8,
            "projectile_speed": 5,
            "damage_type": "fire",
            "burn_chance": 0.55,
            "burn_duration": 4,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 5,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "void_tear": {
            "name": "Void Tear",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 13,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 44,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.8,
            "cooldown": 4.5,
            "range": 310,
            "aoe_radius": 0,
            "accuracy": 0.84,
            "projectile_speed": 9,
            "damage_type": "arcane",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0.3,
            "purge_duration": 3,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "poison_cloud": {
            "name": "Poison Cloud",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 9,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 12,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.4,
            "cooldown": 5.0,
            "range": 270,
            "aoe_radius": 90,
            "accuracy": 0.88,
            "projectile_speed": 5,
            "damage_type": "poison",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0.2,
            "slow_duration": 2.0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "poison_damage": 8,
            "poison_duration": 6,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "dark_pulse": {
            "name": "Dark Pulse",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 11,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 30,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.1,
            "cooldown": 3.5,
            "range": 0,
            "aoe_radius": 140,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "dark",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0.15,
            "stun_duration": 0.75,
            "knockback": 20,
            "lifesteal": 0.1,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "glacier": {
            "name": "Glacier",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 14,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 42,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 2.2,
            "cooldown": 5.5,
            "range": 290,
            "aoe_radius": 55,
            "accuracy": 0.79,
            "projectile_speed": 4,
            "damage_type": "ice",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0.7,
            "slow_duration": 4.0,
            "stun_chance": 0.2,
            "stun_duration": 1.5,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "storm_surge": {
            "name": "Storm Surge",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 16,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 28,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.6,
            "cooldown": 4.0,
            "range": 360,
            "aoe_radius": 0,
            "accuracy": 0.88,
            "projectile_speed": 18,
            "damage_type": "electric",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0.4,
            "stun_duration": 1.2,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 4,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "gale_force": {
            "name": "Gale Force",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 8,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 20,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.8,
            "cooldown": 2.5,
            "range": 300,
            "aoe_radius": 70,
            "accuracy": 0.9,
            "projectile_speed": 20,
            "damage_type": "wind",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 35,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "stone_wall": {
            "name": "Stone Wall",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 10,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 16,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 2.0,
            "cooldown": 6.0,
            "range": 200,
            "aoe_radius": 40,
            "accuracy": 0.85,
            "projectile_speed": 3,
            "damage_type": "earth",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0.5,
            "stun_duration": 2.0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "smite": {
            "name": "Smite",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 7,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 28,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.9,
            "cooldown": 2.8,
            "range": 320,
            "aoe_radius": 0,
            "accuracy": 0.91,
            "projectile_speed": 12,
            "damage_type": "holy",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0.2,
            "stun_duration": 0.8,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0.2,
            "purge_duration": 2,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "soul_rend": {
            "name": "Soul Rend",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 18,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 55,
            "heal_amount": 0,
            "mp_scaling_damage": 0.3,
            "scaling_type": "magic",
            "cast_time": 2.5,
            "cooldown": 7.0,
            "range": 340,
            "aoe_radius": 0,
            "accuracy": 0.8,
            "projectile_speed": 8,
            "damage_type": "arcane",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0.15,
            "chain_targets": 0,
            "purge_chance": 0.5,
            "purge_duration": 4,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "heavenly_judgment": {
            "name": "Heavenly Judgment",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 75,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 0,
            "enemy_dmg_base": 65,
            "heal_amount": 0,
            "mp_scaling_damage": 4.5,
            "scaling_type": "mana_to_damage",
            "cast_time": 2.8,
            "cooldown": 8.0,
            "range": 300,
            "aoe_radius": 120,
            "accuracy": 0.93,
            "projectile_speed": 6,
            "damage_type": "holy",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0.6,
            "purge_duration": 5,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        #!! -- "Magic: Healing" ------------------------------------------------------------------------------------------------

        "heal": {
            "name": "Heal",
            "type": "Spell",
            "buff": False,
            "healing": True,
            "mp_cost": 6,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 0,
            "heal_amount": 27,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.4,
            "cooldown": 3.0,
            "range": 0,
            "aoe_radius": 0,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "holy",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "holy_light": {
            "name": "Holy Light",
            "type": "Spell",
            "buff": False,
            "healing": True,
            "mp_cost": 10,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 18,
            "heal_amount": 22,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.9,
            "cooldown": 4.0,
            "range": 300,
            "aoe_radius": 50,
            "accuracy": 0.82,
            "projectile_speed": 7,
            "damage_type": "holy",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        #!! -- "Magic: Buffs" ------------------------------------------------------------------------------------------------

        "arcane_shield": {
            "name": "Arcane Shield",
            "type": "Spell",
            "buff": True,
            "healing": False,
            "mp_cost": 12,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 0,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.2,
            "cooldown": 8.0,
            "range": 0,
            "aoe_radius": 0,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "arcane",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "damage_absorb",
            "buff_value": 40,
            "buff_duration": 8.0
        },

        "haste": {
            "name": "Haste",
            "type": "Spell",
            "buff": True,
            "healing": False,
            "mp_cost": 10,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 0,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.8,
            "cooldown": 12.0,
            "range": 0,
            "aoe_radius": 0,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "wind",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "speed_boost",
            "buff_value": 0.4,
            "buff_duration": 6.0
        },

        "mana_surge": {
            "name": "Mana Surge",
            "type": "Spell",
            "buff": True,
            "healing": False,
            "mp_cost": 8,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 0,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.0,
            "cooldown": 15.0,
            "range": 0,
            "aoe_radius": 0,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "arcane",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "magic_damage_boost",
            "buff_value": 0.25,
            "buff_duration": 8.0
        },

        "stone_skin": {
            "name": "Stone Skin",
            "type": "Spell",
            "buff": True,
            "healing": False,
            "mp_cost": 9,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 0,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.3,
            "cooldown": 14.0,
            "range": 0,
            "aoe_radius": 0,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "earth",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "defense_boost",
            "buff_value": 12,
            "buff_duration": 10.0
        },

        "clarity": {
            "name": "Clarity",
            "type": "Spell",
            "buff": True,
            "healing": False,
            "mp_cost": 5,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 0,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.6,
            "cooldown": 20.0,
            "range": 0,
            "aoe_radius": 0,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "holy",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "mp_regen",
            "buff_value": 3,
            "buff_duration": 12.0
        },

        #!! -- "Magic: Blood" ------------------------------------------------------------------------------------------------

        "blood_pact": {
            "name": "Blood Pact",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 48,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 2.4,
            "cooldown": 6.0,
            "range": 280,
            "aoe_radius": 0,
            "accuracy": 0.76,
            "projectile_speed": 6,
            "damage_type": "blood",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 14,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "blood_drain": {
            "name": "Blood Drain",
            "type": "Spell",
            "buff": False,
            "healing": False,
            "mp_cost": 25,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 0,
            "enemy_dmg": 40,
            "heal_amount": 0,
            "mp_scaling_damage": 0.2,
            "scaling_type": "magic",
            "cast_time": 1.2,
            "cooldown": 6.0,
            "range": 5,
            "aoe_radius": 0,
            "accuracy": 0.95,
            "projectile_speed": 0,
            "damage_type": "blood",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0.2,
            "slow_duration": 2.0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0.5,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        #!! -- "Technique: Damage" ------------------------------------------------------------------------------------------------

        "power_strike": {
            "name": "Power Strike",
            "type": "Technique",
            "buff": False,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 10,
            "rage_cost": 0,
            "enemy_dmg": 34,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.6,
            "cooldown": 2.5,
            "range": 60,
            "aoe_radius": 0,
            "accuracy": 0.92,
            "projectile_speed": 0,
            "damage_type": "physical",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0.15,
            "stun_duration": 0.5,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "whirlwind": {
            "name": "Whirlwind",
            "type": "Technique",
            "buff": False,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 18,
            "rage_cost": 0,
            "enemy_dmg": 22,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.9,
            "cooldown": 4.0,
            "range": 0,
            "aoe_radius": 80,
            "accuracy": 0.88,
            "projectile_speed": 0,
            "damage_type": "physical",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 25,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "shield_bash": {
            "name": "Shield Bash",
            "type": "Technique",
            "buff": False,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 8,
            "rage_cost": 0,
            "enemy_dmg": 14,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.4,
            "cooldown": 3.0,
            "range": 55,
            "aoe_radius": 0,
            "accuracy": 0.94,
            "projectile_speed": 0,
            "damage_type": "physical",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0.5,
            "stun_duration": 1.2,
            "knockback": 18,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "vault_kick": {
            "name": "Vault Kick",
            "type": "Technique",
            "buff": False,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 14,
            "rage_cost": 0,
            "enemy_dmg": 20,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.5,
            "cooldown": 3.5,
            "range": 70,
            "aoe_radius": 0,
            "accuracy": 0.9,
            "projectile_speed": 0,
            "damage_type": "physical",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0.3,
            "slow_duration": 1.5,
            "stun_chance": 0.25,
            "stun_duration": 0.8,
            "knockback": 30,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        #!! -- "Technique: Buffs" ------------------------------------------------------------------------------------------------

        "clock_up": {
            "name": "Clock Up",
            "type": "Technique",
            "buff": True,
            "healing": False,
            "mp_cost": 8,
            "mp_cost_percent": 0,
            "sp_cost": 15,
            "rage_cost": 0,
            "enemy_dmg": 0,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.3,
            "cooldown": 18.0,
            "range": 0,
            "aoe_radius": 0,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "speed_boost",
            "buff_value": 0.8,
            "buff_duration": 5.0
        },

        "adrenaline": {
            "name": "Adrenaline",
            "type": "Technique",
            "buff": True,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 20,
            "rage_cost": 0,
            "enemy_dmg": 0,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.4,
            "cooldown": 16.0,
            "range": 0,
            "aoe_radius": 0,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "attack_boost",
            "buff_value": 0.3,
            "buff_duration": 7.0
        },

        "iron_stance": {
            "name": "Iron Stance",
            "type": "Technique",
            "buff": True,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 12,
            "rage_cost": 0,
            "enemy_dmg": 0,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.5,
            "cooldown": 14.0,
            "range": 0,
            "aoe_radius": 0,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "knockback_immune",
            "buff_value": 1,
            "buff_duration": 6.0
        },

        #!! -- "Technique: Healing" ------------------------------------------------------------------------------------------------

        "second_wind": {
            "name": "Second Wind",
            "type": "Technique",
            "buff": True,
            "healing": True,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 25,
            "rage_cost": 0,
            "enemy_dmg": 0,
            "heal_amount": 35,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.6,
            "cooldown": 20.0,
            "range": 0,
            "aoe_radius": 0,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "sp_regen",
            "buff_value": 5,
            "buff_duration": 8.0
        },

        #!! -- "Rage: Damage" ------------------------------------------------------------------------------------------------

        "frenzy": {
            "name": "Frenzy",
            "type": "Rage",
            "buff": False,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 20,
            "enemy_dmg": 45,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.3,
            "cooldown": 5.0,
            "range": 65,
            "aoe_radius": 0,
            "accuracy": 0.85,
            "projectile_speed": 0,
            "damage_type": "physical",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0.3,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 8,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "death_wish": {
            "name": "Death Wish",
            "type": "Rage",
            "buff": False,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 50,
            "enemy_dmg": 80,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 1.0,
            "cooldown": 12.0,
            "range": 65,
            "aoe_radius": 0,
            "accuracy": 0.78,
            "projectile_speed": 0,
            "damage_type": "blood",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0.4,
            "stun_duration": 1.5,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 25,
            "buff_name": "",
            "buff_value": 0,
            "buff_duration": 0
        },

        "berserker_charge": {
            "name": "Berserker Charge",
            "type": "Rage",
            "buff": True,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 10,
            "rage_cost": 35,
            "enemy_dmg": 38,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.8,
            "cooldown": 8.0,
            "range": 200,
            "aoe_radius": 30,
            "accuracy": 0.88,
            "projectile_speed": 0,
            "damage_type": "physical",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0.35,
            "stun_duration": 1.0,
            "knockback": 40,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "speed_boost",
            "buff_value": 0.6,
            "buff_duration": 2.0
        },

        #!! -- "Rage: Buffs" ------------------------------------------------------------------------------------------------

        "blood_rage": {
            "name": "Blood Rage",
            "type": "Rage",
            "buff": True,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 30,
            "enemy_dmg": 0,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.5,
            "cooldown": 20.0,
            "range": 0,
            "aoe_radius": 0,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "blood",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "attack_boost",
            "buff_value": 0.5,
            "buff_duration": 10.0,
            "buff_secondary": "lifesteal_boost",
            "buff_secondary_value": 0.2,
            "buff_secondary_duration": 10.0
        },

        "war_cry": {
            "name": "War Cry",
            "type": "Rage",
            "buff": True,
            "healing": False,
            "mp_cost": 0,
            "mp_cost_percent": 0,
            "sp_cost": 0,
            "rage_cost": 25,
            "enemy_dmg": 0,
            "heal_amount": 0,
            "mp_scaling_damage": 0,
            "scaling_type": "",
            "cast_time": 0.6,
            "cooldown": 18.0,
            "range": 0,
            "aoe_radius": 150,
            "accuracy": 1.0,
            "projectile_speed": 0,
            "damage_type": "",
            "burn_chance": 0,
            "burn_duration": 0,
            "slow_chance": 0,
            "slow_duration": 0,
            "stun_chance": 0,
            "stun_duration": 0,
            "knockback": 0,
            "lifesteal": 0,
            "chain_targets": 0,
            "purge_chance": 0,
            "purge_duration": 0,
            "self_damage": 0,
            "buff_name": "attack_boost",
            "buff_value": 0.35,
            "buff_duration": 8.0,
            "debuff_enemy": "attack_reduction",
            "debuff_enemy_value": 0.2,
            "debuff_enemy_duration": 5.0
        },
    }

    @classmethod
    def get_spell(cls, name: str):
        """Retrieves a specific spell from the collection by its name.

        Args:
            name (str): The name of the spell to look up.

        Returns:
            dict | None: The spell data if found, otherwise None.
        """
        return cls.spells.get(name)

    @classmethod
    def get_by_type(cls, spell_type: str, buff: bool | None = None, heal: bool | None = None):
        """Filters and returns spells matching a specific type and optional attributes.

        Args:
            spell_type (str): The category of the ability (e.g., "Spell", "Technique").
            buff (bool | None, optional): Filter by whether the ability is a buff. 
                Defaults to None (ignores buff status).
            heal (bool | None, optional): Filter by whether the ability is a healing ability. 
                Defaults to None (ignores healing status).

        Returns:
            dict: A dictionary of filtered spells matching the given criteria.
        """
        return {
            key: spell
            for key, spell in cls.spells.items()
            if spell["type"] == spell_type
            and (buff is None or bool(spell.get("buff")) == buff)
            and (heal is None or bool(spell.get("healing")) == heal)
        }

    @classmethod
    def all_spells(cls, Buff, Heals):
        """Retrieves all abilities categorized specifically as 'Spell'.

        Args:
            Buff (bool | None): Filter by whether the spell is a buff.
            Heals (bool | None): Filter by whether the spell is a healing spell.

        Returns:
            dict: A dictionary of filtered spells.
        """
        return cls.get_by_type("Spell", Buff, Heals)

    @classmethod
    def all_techniques(cls, Buff, Heals):
        """Retrieves all abilities categorized specifically as 'Technique'.

        Args:
            Buff (bool | None): Filter by whether the technique is a buff.
            Heals (bool | None): Filter by whether the technique is a healing ability.

        Returns:
            dict: A dictionary of filtered techniques.
        """
        return cls.get_by_type("Technique", Buff, Heals)

    @classmethod
    def all_rages(cls, Buff, Heals):
        """Retrieves all abilities categorized specifically as 'Rage'.

        Args:
            Buff (bool | None): Filter by whether the rage ability is a buff.
            Heals (bool | None): Filter by whether the rage ability is a healing ability.

        Returns:
            dict: A dictionary of filtered rage abilities.
        """
        return cls.get_by_type("Rage", Buff, Heals)
    


if __name__ == "__main__":
    all_spells_dict = SpellDataBase.spells

    types = {spell["type"] for spell in all_spells_dict.values()}
    damage_types = {spell["damage_type"] for spell in all_spells_dict.values()}
    
    print([spell.get("buff_name", "") for spell in all_spells_dict.values()])
    print(sorted(types))
    print()
    print(sorted(damage_types))