def get_enemy(name: str):
    return enemy_pool[name]

def all_enemy():
    return enemy_pool

enemy_pool = {
    "goblin": {
        "name": "Goblin",
        "base_lvl": 1,
        "base_hp": 40,
        "max_hp": 40,
        "mp": 5,
        "max_mp": 5,
        "attack": 6,
        "defense": 2,
        "speed": 8,
        "crit": 2,
        "eva": 5,
        "exp_drop": 10,
        "gold_drop": 5,
        "rarity": "common",
        "resistance": {
            "arcane":   0.0,
            "blood":    -0.1,
            "dark":     0.0,
            "earth":    -0.1,
            "electric": 0.1,
            "fire":     0.0,
            "holy":     0.0,
            "ice":      0.0,
            "physical": 0.0,
            "poison":   0.1,
            "wind":     0.0,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "wolf": {
        "name": "Wolf",
        "base_lvl": 2,
        "base_hp": 50,
        "max_hp": 50,
        "mp": 0,
        "max_mp": 0,
        "attack": 8,
        "defense": 3,
        "speed": 12,
        "crit": 6,
        "eva": 10,
        "exp_drop": 14,
        "gold_drop": 6,
        "rarity": "common",
        "resistance": {
            "arcane":   0.0,
            "blood":    0.0,
            "dark":     0.0,
            "earth":    -0.1,
            "electric": 0.1,
            "fire":     -0.1,
            "holy":     0.0,
            "ice":      0.1,
            "physical": 0.0,
            "poison":   0.1,
            "wind":     -0.1,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "orc": {
        "name": "Orc",
        "base_lvl": 3,
        "base_hp": 80,
        "max_hp": 80,
        "mp": 0,
        "max_mp": 0,
        "attack": 12,
        "defense": 6,
        "speed": 6,
        "crit": 3,
        "eva": 3,
        "exp_drop": 25,
        "gold_drop": 12,
        "rarity": "uncommon",
        "resistance": {
            "arcane":   0.0,
            "blood":    -0.1,
            "dark":     0.0,
            "earth":    -0.2,
            "electric": 0.0,
            "fire":     0.1,
            "holy":     0.0,
            "ice":      0.0,
            "physical": 0.0,
            "poison":   0.1,
            "wind":     0.0,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "skeleton": {
        "name": "Skeleton",
        "base_lvl": 2,
        "base_hp": 45,
        "max_hp": 45,
        "mp": 0,
        "max_mp": 0,
        "attack": 9,
        "defense": 4,
        "speed": 7,
        "crit": 4,
        "eva": 4,
        "exp_drop": 16,
        "gold_drop": 8,
        "rarity": "common",
        "resistance": {
            "arcane":   0.1,
            "blood":    -0.5,
            "dark":     0.2,
            "earth":    0.1,
            "electric": 0.0,
            "fire":     0.2,
            "holy":     -0.3,
            "ice":      -0.2,
            "physical": 0.1,
            "poison":   -0.4,
            "wind":     0.0,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "slime": {
        "name": "Slime",
        "base_lvl": 1,
        "base_hp": 35,
        "max_hp": 35,
        "mp": 10,
        "max_mp": 10,
        "attack": 5,
        "defense": 1,
        "speed": 4,
        "crit": 1,
        "eva": 2,
        "exp_drop": 8,
        "gold_drop": 3,
        "rarity": "common",
        "resistance": {
            "arcane":   0.0,
            "blood":    -0.3,
            "dark":     0.0,
            "earth":    -0.1,
            "electric": 0.2,
            "fire":     0.3,
            "holy":     0.0,
            "ice":      -0.1,
            "physical": -0.1,
            "poison":   -0.4,
            "wind":     -0.1,
        },
        "attack_type": "Magician",
        "boss": False
    },

    "bandit": {
        "name": "Bandit",
        "base_lvl": 3,
        "base_hp": 60,
        "max_hp": 60,
        "mp": 5,
        "max_mp": 5,
        "attack": 11,
        "defense": 5,
        "speed": 10,
        "crit": 7,
        "eva": 8,
        "exp_drop": 22,
        "gold_drop": 20,
        "rarity": "uncommon",
        "resistance": {
            "arcane":   0.1,
            "blood":    0.0,
            "dark":     -0.1,
            "earth":    0.0,
            "electric": 0.1,
            "fire":     0.0,
            "holy":     0.1,
            "ice":      0.0,
            "physical": 0.0,
            "poison":   0.0,
            "wind":     0.0,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "troll": {
        "name": "Troll",
        "base_lvl": 5,
        "base_hp": 120,
        "max_hp": 120,
        "mp": 0,
        "max_mp": 0,
        "attack": 18,
        "defense": 10,
        "speed": 3,
        "crit": 2,
        "eva": 1,
        "exp_drop": 40,
        "gold_drop": 18,
        "rarity": "rare",
        "resistance": {
            "arcane":   0.0,
            "blood":    -0.1,
            "dark":     0.0,
            "earth":    -0.2,
            "electric": 0.1,
            "fire":     -0.2,
            "holy":     0.0,
            "ice":      0.1,
            "physical": 0.2,
            "poison":   -0.1,
            "wind":     0.0,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "bat": {
        "name": "Bat",
        "base_lvl": 1,
        "base_hp": 25,
        "max_hp": 25,
        "mp": 0,
        "max_mp": 0,
        "attack": 4,
        "defense": 1,
        "speed": 14,
        "crit": 5,
        "eva": 15,
        "exp_drop": 6,
        "gold_drop": 2,
        "rarity": "common",
        "resistance": {
            "arcane":   0.0,
            "blood":    0.1,
            "dark":     0.1,
            "earth":    0.0,
            "electric": 0.2,
            "fire":     0.0,
            "holy":     -0.1,
            "ice":      0.1,
            "physical": 0.0,
            "poison":   0.0,
            "wind":     -0.1,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "spider": {
        "name": "Spider",
        "base_lvl": 2,
        "base_hp": 40,
        "max_hp": 40,
        "mp": 0,
        "max_mp": 0,
        "attack": 7,
        "defense": 2,
        "speed": 11,
        "crit": 6,
        "eva": 9,
        "exp_drop": 12,
        "gold_drop": 5,
        "rarity": "common",
        "resistance": {
            "arcane":   0.0,
            "blood":    0.0,
            "dark":     -0.1,
            "earth":    -0.1,
            "electric": 0.2,
            "fire":     -0.1,
            "holy":     0.0,
            "ice":      0.1,
            "physical": 0.0,
            "poison":   -0.3,
            "wind":     0.0,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "dark_mage": {
        "name": "Dark Mage",
        "base_lvl": 6,
        "base_hp": 70,
        "max_hp": 70,
        "mp": 40,
        "max_mp": 40,
        "attack": 20,
        "defense": 6,
        "speed": 7,
        "crit": 10,
        "eva": 5,
        "exp_drop": 55,
        "gold_drop": 30,
        "rarity": "rare",
        "resistance": {
            "arcane":   0.2,
            "blood":    0.0,
            "dark":     0.5,
            "earth":    0.0,
            "electric": 0.0,
            "fire":     0.1,
            "holy":     -0.2,
            "ice":      0.0,
            "physical": 0.0,
            "poison":   0.0,
            "wind":     0.0,
        },
        "attack_type": "Magician",
        "boss": False
    },

    "golem": {
        "name": "Golem",
        "base_lvl": 7,
        "base_hp": 160,
        "max_hp": 160,
        "mp": 0,
        "max_mp": 0,
        "attack": 22,
        "defense": 18,
        "speed": 2,
        "crit": 1,
        "eva": 0,
        "exp_drop": 70,
        "gold_drop": 40,
        "rarity": "rare",
        "resistance": {
            "arcane":   -0.1,
            "blood":    -0.5,
            "dark":     0.0,
            "earth":    0.3,
            "electric": 0.2,
            "fire":     -0.3,
            "holy":     0.0,
            "ice":      0.2,
            "physical": 0.3,
            "poison":   -0.5,
            "wind":     -0.2,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "demon_hound": {
        "name": "Demon Hound",
        "base_lvl": 6,
        "base_hp": 100,
        "max_hp": 100,
        "mp": 10,
        "max_mp": 10,
        "attack": 24,
        "defense": 7,
        "speed": 15,
        "crit": 8,
        "eva": 11,
        "exp_drop": 75,
        "gold_drop": 35,
        "rarity": "rare",
        "resistance": {
            "arcane":   -0.1,
            "blood":    0.1,
            "dark":     0.2,
            "earth":    0.0,
            "electric": 0.0,
            "fire":     0.3,
            "holy":     -0.3,
            "ice":      0.0,
            "physical": 0.0,
            "poison":   -0.2,
            "wind":     -0.1,
        },
        "attack_type": "Melee",
        "boss": False
    },

    # --- NEW ENEMIES ---

    "forest_witch": {
        "name": "Forest Witch",
        "base_lvl": 3,
        "base_hp": 55,
        "max_hp": 55,
        "mp": 30,
        "max_mp": 30,
        "attack": 10,
        "defense": 4,
        "speed": 7,
        "crit": 8,
        "eva": 6,
        "exp_drop": 28,
        "gold_drop": 18,
        "rarity": "uncommon",
        "resistance": {
            "arcane":   -0.2,
            "blood":    0.0,
            "dark":     -0.1,
            "earth":    -0.2,
            "electric": 0.0,
            "fire":     0.1,
            "holy":     0.1,
            "ice":      0.0,
            "physical": 0.0,
            "poison":   -0.3,
            "wind":     -0.1,
        },
        "attack_type": "Magician",
        "boss": False
    },

    "plague_rat": {
        "name": "Plague Rat",
        "base_lvl": 1,
        "base_hp": 20,
        "max_hp": 20,
        "mp": 5,
        "max_mp": 5,
        "attack": 4,
        "defense": 1,
        "speed": 13,
        "crit": 3,
        "eva": 11,
        "exp_drop": 7,
        "gold_drop": 2,
        "rarity": "common",
        "resistance": {
            "arcane":   0.0,
            "blood":    0.0,
            "dark":     0.1,
            "earth":    0.0,
            "electric": -0.1,
            "fire":     -0.1,
            "holy":     -0.1,
            "ice":      0.0,
            "physical": 0.0,
            "poison":   -0.4,
            "wind":     0.0,
        },
        "attack_type": "Magician",
        "boss": False
    },

    "mud_elemental": {
        "name": "Mud Elemental",
        "base_lvl": 4,
        "base_hp": 90,
        "max_hp": 90,
        "mp": 20,
        "max_mp": 20,
        "attack": 13,
        "defense": 9,
        "speed": 3,
        "crit": 2,
        "eva": 2,
        "exp_drop": 32,
        "gold_drop": 14,
        "rarity": "uncommon",
        "resistance": {
            "arcane":   0.0,
            "blood":    0.1,
            "dark":     0.0,
            "earth":    -0.4,
            "electric": 0.2,
            "fire":     0.2,
            "holy":     0.0,
            "ice":      -0.1,
            "physical": -0.2,
            "poison":   0.1,
            "wind":     0.1,
        },
        "attack_type": "Magician",
        "boss": False
    },

    "cursed_knight": {
        "name": "Cursed Knight",
        "base_lvl": 5,
        "base_hp": 110,
        "max_hp": 110,
        "mp": 15,
        "max_mp": 15,
        "attack": 17,
        "defense": 12,
        "speed": 5,
        "crit": 5,
        "eva": 4,
        "exp_drop": 45,
        "gold_drop": 28,
        "rarity": "uncommon",
        "resistance": {
            "arcane":   0.1,
            "blood":    0.0,
            "dark":     -0.2,
            "earth":    0.0,
            "electric": 0.0,
            "fire":     0.0,
            "holy":     0.3,
            "ice":      0.1,
            "physical": -0.1,
            "poison":   0.0,
            "wind":     0.0,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "frost_sprite": {
        "name": "Frost Sprite",
        "base_lvl": 3,
        "base_hp": 45,
        "max_hp": 45,
        "mp": 35,
        "max_mp": 35,
        "attack": 11,
        "defense": 3,
        "speed": 10,
        "crit": 7,
        "eva": 8,
        "exp_drop": 24,
        "gold_drop": 14,
        "rarity": "uncommon",
        "resistance": {
            "arcane":   0.0,
            "blood":    0.0,
            "dark":     0.0,
            "earth":    0.0,
            "electric": 0.1,
            "fire":     0.3,
            "holy":     0.0,
            "ice":      -0.5,
            "physical": 0.0,
            "poison":   0.0,
            "wind":     -0.1,
        },
        "attack_type": "Magician",
        "boss": False
    },

    "shadow_thief": {
        "name": "Shadow Thief",
        "base_lvl": 4,
        "base_hp": 65,
        "max_hp": 65,
        "mp": 10,
        "max_mp": 10,
        "attack": 14,
        "defense": 4,
        "speed": 14,
        "crit": 10,
        "eva": 13,
        "exp_drop": 35,
        "gold_drop": 30,
        "rarity": "uncommon",
        "resistance": {
            "arcane":   0.1,
            "blood":    0.0,
            "dark":     -0.3,
            "earth":    0.0,
            "electric": 0.0,
            "fire":     0.0,
            "holy":     0.2,
            "ice":      0.0,
            "physical": 0.0,
            "poison":   0.1,
            "wind":     0.1,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "storm_hawk": {
        "name": "Storm Hawk",
        "base_lvl": 4,
        "base_hp": 60,
        "max_hp": 60,
        "mp": 0,
        "max_mp": 0,
        "attack": 13,
        "defense": 3,
        "speed": 16,
        "crit": 8,
        "eva": 14,
        "exp_drop": 30,
        "gold_drop": 16,
        "rarity": "uncommon",
        "resistance": {
            "arcane":   0.0,
            "blood":    0.0,
            "dark":     0.0,
            "earth":    0.0,
            "electric": -0.3,
            "fire":     0.0,
            "holy":     0.0,
            "ice":      0.1,
            "physical": 0.0,
            "poison":   0.0,
            "wind":     -0.4,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "swamp_witch": {
        "name": "Swamp Witch",
        "base_lvl": 5,
        "base_hp": 75,
        "max_hp": 75,
        "mp": 45,
        "max_mp": 45,
        "attack": 16,
        "defense": 5,
        "speed": 6,
        "crit": 9,
        "eva": 5,
        "exp_drop": 48,
        "gold_drop": 32,
        "rarity": "rare",
        "resistance": {
            "arcane":   -0.1,
            "blood":    0.1,
            "dark":     -0.2,
            "earth":    -0.3,
            "electric": 0.0,
            "fire":     0.1,
            "holy":     0.2,
            "ice":      0.0,
            "physical": 0.0,
            "poison":   -0.4,
            "wind":     0.0,
        },
        "attack_type": "Magician",
        "boss": False
    },

    "blood_wraith": {
        "name": "Blood Wraith",
        "base_lvl": 6,
        "base_hp": 85,
        "max_hp": 85,
        "mp": 30,
        "max_mp": 30,
        "attack": 19,
        "defense": 7,
        "speed": 9,
        "crit": 11,
        "eva": 8,
        "exp_drop": 60,
        "gold_drop": 38,
        "rarity": "rare",
        "resistance": {
            "arcane":   0.1,
            "blood":    -0.5,
            "dark":     -0.2,
            "earth":    0.0,
            "electric": 0.0,
            "fire":     0.0,
            "holy":     0.3,
            "ice":      0.1,
            "physical": 0.1,
            "poison":   0.0,
            "wind":     0.0,
        },
        "attack_type": "Magician",
        "boss": False
    },

    "iron_golem": {
        "name": "Iron Golem",
        "base_lvl": 6,
        "base_hp": 140,
        "max_hp": 140,
        "mp": 0,
        "max_mp": 0,
        "attack": 20,
        "defense": 16,
        "speed": 2,
        "crit": 1,
        "eva": 0,
        "exp_drop": 65,
        "gold_drop": 38,
        "rarity": "rare",
        "resistance": {
            "arcane":   0.0,
            "blood":    -0.4,
            "dark":     0.0,
            "earth":    0.2,
            "electric": 0.3,
            "fire":     -0.2,
            "holy":     0.0,
            "ice":      0.1,
            "physical": 0.4,
            "poison":   -0.5,
            "wind":     0.1,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "void_stalker": {
        "name": "Void Stalker",
        "base_lvl": 7,
        "base_hp": 95,
        "max_hp": 95,
        "mp": 35,
        "max_mp": 35,
        "attack": 22,
        "defense": 8,
        "speed": 13,
        "crit": 12,
        "eva": 10,
        "exp_drop": 80,
        "gold_drop": 50,
        "rarity": "rare",
        "resistance": {
            "arcane":   -0.3,
            "blood":    0.0,
            "dark":     -0.4,
            "earth":    0.0,
            "electric": 0.1,
            "fire":     0.0,
            "holy":     0.2,
            "ice":      0.0,
            "physical": 0.1,
            "poison":   0.0,
            "wind":     0.1,
        },
        "attack_type": "Magician",
        "boss": False
    },

    "plague_doctor": {
        "name": "Plague Doctor",
        "base_lvl": 7,
        "base_hp": 80,
        "max_hp": 80,
        "mp": 50,
        "max_mp": 50,
        "attack": 21,
        "defense": 7,
        "speed": 7,
        "crit": 11,
        "eva": 6,
        "exp_drop": 85,
        "gold_drop": 55,
        "rarity": "rare",
        "resistance": {
            "arcane":   0.0,
            "blood":    0.1,
            "dark":     0.1,
            "earth":    0.0,
            "electric": 0.0,
            "fire":     -0.1,
            "holy":     -0.1,
            "ice":      0.0,
            "physical": 0.0,
            "poison":   -0.5,
            "wind":     0.0,
        },
        "attack_type": "Magician",
        "boss": False
    },

    "stone_titan": {
        "name": "Stone Titan",
        "base_lvl": 8,
        "base_hp": 180,
        "max_hp": 180,
        "mp": 0,
        "max_mp": 0,
        "attack": 26,
        "defense": 20,
        "speed": 2,
        "crit": 2,
        "eva": 1,
        "exp_drop": 95,
        "gold_drop": 65,
        "rarity": "epic",
        "resistance": {
            "arcane":   0.0,
            "blood":    -0.3,
            "dark":     0.0,
            "earth":    0.4,
            "electric": 0.2,
            "fire":     -0.2,
            "holy":     0.0,
            "ice":      -0.1,
            "physical": 0.3,
            "poison":   -0.4,
            "wind":     0.1,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "soul_eater": {
        "name": "Soul Eater",
        "base_lvl": 8,
        "base_hp": 105,
        "max_hp": 105,
        "mp": 55,
        "max_mp": 55,
        "attack": 24,
        "defense": 9,
        "speed": 10,
        "crit": 13,
        "eva": 9,
        "exp_drop": 100,
        "gold_drop": 70,
        "rarity": "epic",
        "resistance": {
            "arcane":   -0.3,
            "blood":    -0.2,
            "dark":     -0.4,
            "earth":    0.0,
            "electric": 0.0,
            "fire":     0.0,
            "holy":     0.4,
            "ice":      0.0,
            "physical": 0.1,
            "poison":   0.1,
            "wind":     0.0,
        },
        "attack_type": "Magician",
        "boss": False
    },

    "frost_giant": {
        "name": "Frost Giant",
        "base_lvl": 9,
        "base_hp": 170,
        "max_hp": 170,
        "mp": 0,
        "max_mp": 0,
        "attack": 30,
        "defense": 14,
        "speed": 4,
        "crit": 5,
        "eva": 3,
        "exp_drop": 115,
        "gold_drop": 85,
        "rarity": "epic",
        "resistance": {
            "arcane":   0.0,
            "blood":    0.0,
            "dark":     0.0,
            "earth":    0.1,
            "electric": 0.1,
            "fire":     0.4,
            "holy":     0.0,
            "ice":      -0.5,
            "physical": -0.1,
            "poison":   0.0,
            "wind":     -0.2,
        },
        "attack_type": "Melee",
        "boss": False
    },

    "lich": {
        "name": "Lich",
        "base_lvl": 9,
        "base_hp": 115,
        "max_hp": 115,
        "mp": 70,
        "max_mp": 70,
        "attack": 27,
        "defense": 10,
        "speed": 6,
        "crit": 14,
        "eva": 5,
        "exp_drop": 120,
        "gold_drop": 90,
        "rarity": "epic",
        "resistance": {
            "arcane":   -0.3,
            "blood":    0.3,
            "dark":     -0.5,
            "earth":    0.0,
            "electric": 0.0,
            "fire":     0.0,
            "holy":     0.4,
            "ice":      -0.1,
            "physical": 0.1,
            "poison":   0.3,
            "wind":     0.0,
        },
        "attack_type": "Magician",
        "boss": False
    },

    # --- BOSSES ---

    "necromancer": {
        "name": "Necromancer",
        "base_lvl": 8,
        "base_hp": 90,
        "max_hp": 90,
        "mp": 60,
        "max_mp": 60,
        "attack": 25,
        "defense": 8,
        "speed": 6,
        "crit": 12,
        "eva": 4,
        "exp_drop": 90,
        "gold_drop": 60,
        "rarity": "epic",
        "resistance": {
            "arcane":   0.2,
            "blood":    -0.1,
            "dark":     0.6,
            "earth":    0.0,
            "electric": 0.0,
            "fire":     0.0,
            "holy":     -0.4,
            "ice":      0.0,
            "physical": 0.0,
            "poison":   -0.2,
            "wind":     0.0,
        },
        "attack_type": "Magician",
        "boss": True
    },

    "wyvern": {
        "name": "Wyvern",
        "base_lvl": 9,
        "base_hp": 140,
        "max_hp": 140,
        "mp": 20,
        "max_mp": 20,
        "attack": 28,
        "defense": 10,
        "speed": 16,
        "crit": 9,
        "eva": 12,
        "exp_drop": 110,
        "gold_drop": 80,
        "rarity": "epic",
        "resistance": {
            "arcane":   0.0,
            "blood":    0.0,
            "dark":     0.0,
            "earth":    0.0,
            "electric": 0.2,
            "fire":     0.2,
            "holy":     0.0,
            "ice":      -0.2,
            "physical": 0.1,
            "poison":   -0.1,
            "wind":     0.2,
        },
        "attack_type": "Melee",
        "boss": True
    },

    "shadow_lord": {
        "name": "Shadow Lord",
        "base_lvl": 10,
        "base_hp": 180,
        "max_hp": 180,
        "mp": 80,
        "max_mp": 80,
        "attack": 32,
        "defense": 14,
        "speed": 10,
        "crit": 15,
        "eva": 10,
        "exp_drop": 160,
        "gold_drop": 130,
        "rarity": "legendary",
        "resistance": {
            "arcane":   -0.2,
            "blood":    0.1,
            "dark":     -0.6,
            "earth":    0.0,
            "electric": 0.0,
            "fire":     0.0,
            "holy":     0.4,
            "ice":      0.0,
            "physical": 0.1,
            "poison":   0.1,
            "wind":     0.0,
        },
        "attack_type": "Magician",
        "boss": True
    },

    "ancient_guardian": {
        "name": "Ancient Guardian",
        "base_lvl": 10,
        "base_hp": 220,
        "max_hp": 220,
        "mp": 30,
        "max_mp": 30,
        "attack": 35,
        "defense": 25,
        "speed": 4,
        "crit": 5,
        "eva": 2,
        "exp_drop": 150,
        "gold_drop": 120,
        "rarity": "legendary",
        "resistance": {
            "arcane":   0.2,
            "blood":    -0.3,
            "dark":     0.2,
            "earth":    0.3,
            "electric": 0.2,
            "fire":     0.0,
            "holy":     0.2,
            "ice":      0.0,
            "physical": 0.4,
            "poison":   -0.2,
            "wind":     0.0,
        },
        "attack_type": "Melee",
        "boss": True
    },

    "infernal_titan": {
        "name": "Infernal Titan",
        "base_lvl": 11,
        "base_hp": 260,
        "max_hp": 260,
        "mp": 40,
        "max_mp": 40,
        "attack": 40,
        "defense": 22,
        "speed": 5,
        "crit": 8,
        "eva": 3,
        "exp_drop": 200,
        "gold_drop": 160,
        "rarity": "legendary",
        "resistance": {
            "arcane":   0.0,
            "blood":    0.0,
            "dark":     0.1,
            "earth":    -0.2,
            "electric": -0.1,
            "fire":     -0.6,
            "holy":     -0.1,
            "ice":      0.4,
            "physical": -0.2,
            "poison":   0.1,
            "wind":     0.0,
        },
        "attack_type": "Melee",
        "boss": True
    },

    "void_archon": {
        "name": "Void Archon",
        "base_lvl": 12,
        "base_hp": 240,
        "max_hp": 240,
        "mp": 100,
        "max_mp": 100,
        "attack": 38,
        "defense": 18,
        "speed": 9,
        "crit": 16,
        "eva": 8,
        "exp_drop": 220,
        "gold_drop": 180,
        "rarity": "legendary",
        "resistance": {
            "arcane":   -0.5,
            "blood":    0.0,
            "dark":     -0.4,
            "earth":    0.1,
            "electric": 0.1,
            "fire":     0.0,
            "holy":     0.3,
            "ice":      0.0,
            "physical": 0.2,
            "poison":   0.0,
            "wind":     0.1,
        },
        "attack_type": "Magician",
        "boss": True
    },
}